version: '3.5'
services:
  goal_mysql:
    image: "mysql:5.7"
    container_name: goal_mysql
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - "./runtime/mysql/data:/var/lib/mysql"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
#    networks:
#      - backend

  goal_redis:
    image: redis
    container_name: goal_redis
    restart: always
    ports:
      - "36379:6379"
    volumes:
      - "./runtime/redis/data:/data"
      - "./runtime/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      redis-server /usr/local/etc/redis/redis.conf
#    networks:
#      - backend

  goal_api:
    image: goal
    container_name: goal_api_service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./.env:/app/.env"
      - "./runtime/logs/api:/app/log"
    environment:
      ENV_NAME: ".env"
      APP_SERVICE: "api"
    links:
      - goal_mysql
      - goal_redis
    depends_on:
      - goal_mysql
      - goal_redis
    command:
      goal
#      networks:
#        - backend


  goal_admin:
    image: goal
    container_name: goal_admin_service
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - "./.env:/app/.env"
      - "./runtime/logs/admin:/app/log"
    environment:
      ENV_NAME: ".env"
      APP_SERVICE: "admin"
    links:
      - goal_mysql
      - goal_redis
    depends_on:
      - goal_mysql
      - goal_redis
    command:
      goal
#    networks:
#      - backend

#networks:
#  backend:
#    name: goal_network
#    driver: bridge